### ISSUE TITLE
ドキュメント(*.md)についての話の場

### ISSUE THREAD

**Issue by take-w** [YOODS/rovi#10]
@KazukiHiraizumi @Kan-Harada 
ドキュメント(*.md)についてコメントできるようにIssueを発行しました。

ひとまず1個だけ↓。

Calibration.md
の最後の方に
「ROSのクセですが、：の後にはスペースが必要なので注意しましょう」
とありますが、
コロンの後ろにスペースが必要なのは（ROSのクセというより）YAMLの仕様なので、
（…ROS ParameterもdynparamもYAML文法で書くようになっている…）

「パラメータ書式はYAML文法にしたがうため、：の後にはスペースが必要なので注意しましょう」
などでいかがでしょうか。

**Comment by take-w** [comment]
GettingStarted.mdもとりあえず書いた（実行手順は大枠のみ）ので、チェック＆コメントお願いします。

**Comment by KazukiHiraizumi** [comment]
動かせるまでの手順はなかなか多いですね。
1. npmで必須ものはrosnodejsだけでは？
2. RoVI起動のあとに「動作確認」のセクションが要りそう
   1. ライブ画像のViewing方法（Topic）
   2. 点群画像のViewing方法

点群は未だ出ないので、ライブの動作までを誰かに実験台になってもらいましょう

**Comment by KazukiHiraizumi** [comment]
さらにそのあと、「撮影調整」みたいなセクションで、GainやExposureの調整手順が要りますね。私も基準が何なのか分からないですが・・・
- Parameter一覧
- Topic一覧
- Service一覧
は話が細かくなるので、別紙の詳細マニュアルに記載した方がいいように思います。

**Comment by take-w** [comment]
npm install ws
npm install opencv
npm install canvas
はブラウザでのアレコレのためでしたでしょうか。

となると今回は
npm install ws
npm install canvas
はインストール不要は確定。

ただ、
npm install opencv
については、その中でインストールされる
minimist
js-yaml
というのをjs内で使っています。
（前者は起動引数解釈、後者はYAML文法解釈）

なので、以下のどちらかになります。どうしましょう？

＜A＞
npm install opencv
（上記minimistとjs-yamlのため。将来opencvが必要になった場合に備えても。）

＜B＞
npm install minimist
npm install js-yaml
（はっきり2つ入れる。）

**Comment by take-w** [comment]
> 最後の最後に(Appendixかな)、
> Parameter一覧
> Topic一覧
> Service一覧

了解です。（これらをどこに書くか悩んでました。Appendixにします。）
