### ISSUE TITLE
shm-typed-arrayのBuildできない

### ISSUE THREAD

**Issue by KazukiHiraizumi** [YOODS/rovi#15]
~~~
 node-gyp configure
~~~
時に、
~~~
module.js:549
throw err;

Error: Cannot find module 'graceful-fs'
~~~
となりBuildできません

**Comment by take-w** [comment]
↓でOKでした。
（ビルドはRoVIローカルディレクトリで行う。
　ycam1s.jsもそのRoVIローカルのを使う。
　/usr/lib/node_modules/shm-typed-array/は出番なし。
　グローバルなのはnode-gypのインストールのみ。）

＝＝＝＝↓ここから↓＝＝＝＝
cd ~/catkin_ws/src/rovi/shm-typed-array/
npm install nan
npm install node-cleanup
sudo npm install -g node-gyp（★）
node-gyp configure
node-gyp build
＝＝＝＝↑ここまで↑＝＝＝＝

★のところで、これまではsudo apt-get install node-gypしていたのがまずかったみたい。
（単にnode-gypすると、そうやってインストールしろ、というメッセージが出るので
　その罠にはまっていた。）
