### ISSUE TITLE
ライブ生画像もimage topicにpublishした方がよいのでは

### ISSUE THREAD

**Issue by take-w** [YOODS/rovi#17]
@KazukiHiraizumi 
以前はcamera_aravis::camnodeが画像を
/rovi/cam_l/camera/image_raw
/rovi/cam_r/camera/image_raw
にpublishしていたが、
camera_aravis::camnodeがいなくなったので、
現状ではライブ映像をtopicで確認できない。

pshift_genpc.jsで、remapする前の生画像もpublishした方が良いと思いますがどうでしょうか。

**Comment by KazukiHiraizumi** [comment]
ああほんまですね。pshift_genpc.jsに追加します。
image_rectとの一貫性を考えると、topic名はcamera/以下ではなく
/rovi/cam_l/image_raw
/rovi/cam_r/image_raw
にしたいですがどうでしょう？

**Comment by take-w** [comment]
その2つのtopicにライブ生画像が出ることを確認しました。
