### ISSUE TITLE
grabberでも画像が重なって来る(たぶんドライバが再送要求する)

### ISSUE THREAD

**Issue by KazukiHiraizumi** [YOODS/rovi#19]
sentechのSDKを使ったgrabberの単体テストでも、カメラ２台では重複が来る。
この現象はUDPの衝突が起きることで、リトライがかかっていることが原因かもしれない。
Issue#12もaravisのせいではなかったのかも・・・

**Comment by KazukiHiraizumi** [comment]
対策としては、
1. TriggerMode=Offコマンドを左右で時間差(1frameの送信時間、CMOS⇒GVが律速)をつける。
2. TriggerMode=Softwareとし左右交互にSoftwareTriggerコマンドを送る
3. PICに周期パルス発生モードを追加する
どうしようか？時間ないな。。。

**Comment by KazukiHiraizumi** [comment]
３．が正解ですね。PIC書き換えます。
これなら、パケット送出ディレイ(GevSCPD？？）とやらいうやつを正しく調整すれば、ライブも位相シフトも
同じになる。

**Comment by Kan-Harada** [comment]
これって、「カメラに送るトリガを1フレーム分ずらす」、ということでしょうか。位相シフトの場合、プロジェクタとの同期が必要なので、それは無理と思いますが・・・勘違いでしょうか?
それぞれのカメラのパケットはパケット自体に含まれるカメラIDで区別されている筈なので、それがテレコになるということは受信側の問題な気がします。

**Comment by KazukiHiraizumi** [comment]
@Kan-Harada 
Issue#11にも上げてますが、
https://www.baslerweb.com/fp-1481127658/media/downloads/documents/application_notes/AW00064902000_Controlling_Packet_Timing_With_Delays.pdf
パケット衝突が起きると、ドライバーがエラーと認識して再送要求するのではないかと推測です。
対策として左カメラの１パケット(＝MTU)分の送出時間だけ右カメラの送出を遅らせる。
このディレイは数10μｓなので、ハードトリガでもソフトトリガでも調整は無理ですが、外部トリガなら可能かな・・・
もし原因がそこなら１週間ロスですね。痛い・・・

**Comment by KazukiHiraizumi** [comment]
Baslerのドキュメントでは,ドライバーにPacket Timeout(Inter-packet-delay)とやら設定があって、これでPacket間のintervalを監視しているらしい。Sentechにも同様機能はあるはずなので
4. 受信側(ドライバ)での対応
言う手も確かにあるねえ。

**Comment by Kan-Harada** [comment]
先ほど中尾さんに確認したところ、windowsでリリースしているソフトウェアでは特に特殊なコーディング無しで同時トリガで動いているようです。

カメラ側にはディレイ設定をいれているらしらく、それが

> aslerのドキュメントでは,ドライバーにPacket Timeout(Inter-packet-delay)とやら設定があって、これでPacket間のintervalを監視しているらしい。

に相当するものでしょうか。それであれば、カメラ初期化時に設定するだけですが、これも中尾さんに確認したところ、「竹林さんはそれは入れた、ときいてる」という話ですが・・・

**Comment by KazukiHiraizumi** [comment]
外部トリガーモードの時は多分TriggerDelay?いうのを設定するのかなと思います。
しかしMTU9000だと、このディレイは１００μｓ以下なので、ストリーミング(今はハードトリガもしくはソフトトリガ)も外部トリガに変更しないと、タイミングが合わないですね。
さっきPICのプログラムに定周期パルスを出すコマンドを追加したので、まずは対策３でやってみましょう

**Comment by Kan-Harada** [comment]
了解しました。

[dlp.pdf](https://github.com/YOODS/rovi/files/1892375/dlp.pdf)

DLPの動きを説明している資料ですが、実際問題としてDLPの発光とカメラトリガがどの程度同期しているかという確認作業が必要!! という話は別にして、下位1,2ビットの発光を捨ててしまうことにはなりそうです。

実際には発光パターンは5,6ビットあれば十分な気もしますが・・・

**Comment by KazukiHiraizumi** [comment]
Basleのドキュメントだと、同一ネットに２台以上のカメラがあるときは、送出遅延を設定してパケット衝突が起きないようにしましょう、ということです。
カメラのトリガーは同時、i.e. CMOSの露光も同時ということが前提で書いてあります。
なのですが、TriggerDelayという設定はあるのですが、そのパケットディレイ的なものが見当たらない・・・

中尾さん：
Win版では、このディレイを何と言うパラメータを設定していますか？
