### ISSUE TITLE
GVCPカメラ制御仕様

### ISSUE THREAD

**Issue by Kan-Harada** [YOODS/rovi#21]
[GVCPカメラ制御仕様.txt](https://github.com/YOODS/rovi/files/1915075/GVCP.txt)

GVCPの仕様です。レビューをお願いします。

**Comment by KazukiHiraizumi** [comment]
UART仕様よくわからないのでDRやってください

**Comment by KazukiHiraizumi** [comment]
【設計検証記録】
<table>
<tr><th>項目<th>アドレス<th>結果
<tr><td>画像転送<td>-<td>？画像を明るくするとフリーズする
<tr><td>フレームレート <td>0x00101000<td>OK
<tr><td>露光時間<td>0x00101004<td>OK
<tr><td>アナログゲイン<td>0x00101008<td>OK
<tr><td>デジタルゲイン<td>0x0010100C<td>OK
<tr><td>トリガーモード<td>0x00101010<td>？Acquision=Offでのみ有効。常時反映されるよう改修中
<tr><td>シリアルポート<td>0x00300004<td>未確認
</table>
