### ISSUE TITLE
OpenCVバージョン問題

### ISSUE THREAD

**Issue by KazukiHiraizumi** [YOODS/rovi#25]
@Kan-Harada
ROSのインストール時に/opt/ros/kinetic/lib以下にOpenCVのContribも含めインストールされているので、これでリンク出来ないとは、ちょっと考えられないです。
OpenCV(cv_bridge)つかう他のノードでもバージョンの齟齬問題はないので、何でこれだけ？ぜひ統一ねがいます。Javaみたいで嫌なります

**Comment by Kan-Harada** [comment]
了解しました。OpenCVのFileStorageクラスあたりにひっかかっているぽいので、この周りをもう少し調べてみます。それでもaptでインストールしたOpenCVではだめな場合はFileStrageを使わず、自力でFileI/Oを書く等で回避するようにします。

**Comment by Kan-Harada** [comment]
よくわからないトラブルでしたが、位相シフトライブラリは/usr/libにインストールされているOpenCVをリンクするようにMakefileを書いていました。

ROSで使っているOpenCVが/usr/libのOpenCVではなく、「/opt/rosにインストールされているOpenCVである」ということで、include, libの場所指示を変えてみたところ、問題なくコンパイル・リンクは通ります。

/usr/libにaptでインストールされているものはOpenCV2.4ベースです。/opt/rosにインストールされているものはOpenCV3.3です。これがリンクエラーの原因ですね。

※PCの場合はこれで解決ですが、JETSONの場合
JETSONにJetpackでインストールされるOpenCVは/usr/libに入り、GPU対応になっています。一方、/opt/rosのOpenCV3.3は非GPU版でしょう。自分でソースからビルドするOpenCV3.3はGPU対応にしてあるので、いずれにしてもJETSON上で使う場合はこの後者の対応が必要になります。

**Comment by KazukiHiraizumi** [comment]
lib/x86_64以下のlibopencv*が200MB以上あって結構エグいですが、これは消して大丈夫ですね。

**Comment by KazukiHiraizumi** [comment]
objdumpでみたら未だ
~~~
NEEDED               libopencv_core.so.3.4
NEEDED               libopencv_calib3d.so.3.4
NEEDED               libopencv_imgproc.so.3.4
~~~
ですね

**Comment by KazukiHiraizumi** [comment]
Kineticは3.3.1-dev（3.4）
