### ISSUE TITLE
ycam3vgaのlaunchでたまに /rovi/"regw" not available と出て起動しない

### ISSUE THREAD

**Issue by take-w** [YOODS/rovi#27]
@KazukiHiraizumi 
camera_aravisのサービスが準備出来ていないというエラー？

↓こういう感じです。

take@take-NXC154:~/catkin_ws$ roslaunch rovi run-ycam3vga.launch
[WARN] [1526897554.236] (ros): No camera params for L/R
[ERROR] [1526897559.260] (ros): /rovi/"regw" not available
[ERROR] [1526897559.261] (ros): Failure in openCamera
[rovi/pshift_genpc-6] process has died [pid 4381, exit code 101, cmd /home/take/catkin_ws/src/rovi/script/pshift_genpc.js ycam3 __name:=pshift_genpc __log:=/home/take/.ros/log/7a4e62ea-5cdf-11e8-b64e-a434d98edfe6/rovi-pshift_genpc-6.log].
log file: /home/take/.ros/log/7a4e62ea-5cdf-11e8-b64e-a434d98edfe6/rovi-pshift_genpc-6*.log
^C
take@take-NXC154:~/catkin_ws$

**Comment by KazukiHiraizumi** [comment]
rosserviceでみても/rovi/camera/regwがいてないですか？

**Comment by take-w** [comment]
いないです。

このエラー状態だと↓になっています。
take@take-NXC154:~$ rosservice list | grep /rovi/camera
/rovi/camera/get_loggers
/rovi/camera/set_camera_info
/rovi/camera/set_logger_level
/rovi/camera/set_parameters

正常時だと↓です。
take@take-NXC154:~$ rosservice list | grep /rovi/camera
/rovi/camera/get_loggers
/rovi/camera/image_raw/compressed/set_parameters
/rovi/camera/image_raw/compressedDepth/set_parameters
/rovi/camera/image_raw/theora/set_parameters
/rovi/camera/queue
/rovi/camera/regr
/rovi/camera/regw
/rovi/camera/set_camera_info
/rovi/camera/set_logger_level
/rovi/camera/set_parameters

あ、YCAM3D-IIIの電源をOFF->ONすると直るようです。

**Comment by KazukiHiraizumi** [comment]
CreateStreamあたりで無限ループてるっぽい
ユーザがトラブルシュートできればいいとしましょう
トラブルシューティングのリスト化します

**Comment by take-w** [comment]
> CreateStreamあたりで無限ループてる

そのようです。

**Comment by take-w** [comment]
> YCAM3D-IIIの電源をOFF->ONすると直るようです。

直らないことも多いようです。

その場合、
YCAM3D-IIIの電源OFF->ONやLANのOFF->ONでは直らず、
PCを再起動したら直ります。。

直らない状態でも
roscore
rosrun camera_aravis camnode
であればregwなどできていて動くのですが。
（それを考え合わせると、
　RoVIが自身の起動を貫いて何かファイルなどに情報を書いていて、
　それが問題の原因になっているとか？🤔）

**Comment by take-w** [comment]
（現在開発用にPCでやってますが）
常にPC再起動後初回だけOKで、以降はPC再起動するまで常に
/rovi/"regw" not available
となる、、
という状況でした。

で、よく調べてみると、Issue #31の対応として入れた
> 現在はlaunch/ycam3vga.launchの先頭でsetgev.shを実行して
> 　arv-tool-0.4 control GevSCPSPacketSize=9000

の影響でそうなっています。

RoVIを一回実行して停止した後、
次回RoVIの先頭での
> arv-tool-0.4 control GevSCPSPacketSize=9000

を実行すると、その次のcamnodeが「CreateStreamあたりで無限ループ」です。

この
> arv-tool-0.4 control GevSCPSPacketSize=9000

は
arv-tool-0.4 control [○○]
arv-tool-0.4 features
arv-tool-0.4 genicam
などでも無限ループになります。

arv-tool-0.4 --help
の場合は無限ループにならずOK

**Comment by take-w** [comment]
arv-tool-0.4 control GevSCPSPacketSize=9000
はIssue #31の
> （★最終的な解決としてはYCAM3D-III側の出荷時デフォルト値を9000にする必要がある。）

によって不要にはなるのですが、
パラメータ（DKRPQなど）をYCAMのgenicam XMLから取得する、
という話になっていて、そうすると
> arv-tool-0.4 genicam
でやはりおかしくなります。。

**Comment by take-w** [comment]
↑けど、

arv-tool-0.4 genicamはcamnode起動前に打つと
（arv-tool-0.4 controlと同様に）今回の問題が起こるが、

camnodeがつながった後に打てば問題は起こらずにgenicam XML取得＆regwなどOK、

でした。

**Comment by take-w** [comment]
不思議なことに、
Jetsonでは
arv-tool-0.4 control GevSCPSPacketSize=9000
をcamnode起動前に打っても問題起こらないですね。
（Jetson再起動など不要。）

PCでは再起動しないといけない、となる。
（なのでPCの場合は
arv-tool-0.4 control GevSCPSPacketSize=9000
を一時的にコメントアウトして実装は進められる。）

⇒しかし
>（★最終的な解決としてはYCAM3D-III側の出荷時デフォルト値を9000にする必要がある。）

がうれしい。

**Comment by take-w** [comment]
PCでのこの再起動しないと直らない問題は別途Issueにします。

（本来のこの#27の「たまに」/rovi/"regw" not available）はこのままこの#27で。
