### ISSUE TITLE
Publish->Subscribeのスループット

### ISSUE THREAD

**Issue by KazukiHiraizumi** [YOODS/rovi#36]
1.3MB画像データをloopbackにてpub-subするスループットを計測。

|time to publish|time to subscribe|diff|
|:----|:----|:----|
|1531621775.659798|1531621775.670|0.010|
|1531621916.166472|1531621916.177|0.011|
|1531621935.132970|1531621935.142|0.009|

約１００MB/sくらいのスループット
メモリ転送の1/10のオーダ

**Comment by KazukiHiraizumi** [comment]
Pub-SubよりService callを多用しているので、この部分はどうせ外からは見えないことから、Imageメッセージの仕様を拡張してはどうか
1. 通常はImage構造体のdata要素がビットマップデータであるが、これを共有メモリキー(4byte)にする
2. Server側はメッセージを受け取って共有メモリキーでメモリをアサインする
3. 画像データのヘッダなどの付加情報はメッセージで受け取るので、それを使ってビットマップデータを再現する
4. Topicとかへ出してもViewerでは見れないので注意
5. 内部的にはdata長が4bytesならキー、それ以上であればビットマップと判別しようか

私のアカウントでテストしました。
https://github.com/KazukiHiraizumi/ShImage
C++とNodejsはこれでイメージデータはメモリ渡しになる。
Pythonにも共有メモリのライブラリあれば最強だが・・・

**Comment by k-okada** [comment]
共有メモリができるということは，同じマシンで動かしているんだとおもいますが，その場合はnodeletを使うのが良いとおもいます．
これで，シリアライズもせずに直にメモリコピーされるはずです．
https://github.com/ros-drivers/freenect_stack/blob/master/freenect_camera/src/nodes/freenect_node.cpp
https://github.com/ros-perception/opencv_apps/blob/indigo/src/node/standalone_nodelet_exec.cpp.in

--
◉ Kei Okada


2018年7月16日 21:28 Kazuki Hiraizumi <notifications@github.com>:

**Comment by KazukiHiraizumi** [comment]
Nodelet化は先週の実装委員会でも但馬さんからご指摘いただきました。
よくよく考えたら、C言語Onlyではなかったので、共有メモリー渡しを検討しているとこです。
未だ実装はしてないです。
