### ISSUE TITLE
不具合いろいろ

### ISSUE THREAD

**Issue by KazukiHiraizumi** [YOODS/rovi#54]
1. grid_node
ボードのパラメータが不適の時、136行目で例外
broadcaster->sendTransform(transformStamped);
transform::rotationがnan値のよう

**Comment by KazukiHiraizumi** [comment]
2. grid_node
gamma=1以外だと死ぬ

**Comment by Kan-Harada** [comment]
再現しました。未知のexceptionか？と調べましたがそうではないようです。川村さんにgamma correctionの扱いを調べてもらいますが、当面gamma_correction=1.0ｄ使っておいてください。画面が明るければ特に問題ないと思います。

**Comment by KazukiHiraizumi** [comment]
3. ycamctl
- ~~撮像トリガが効かなくなる~~
- ~~EventEmitterにMemoryLeak~~[済]
