### ISSUE TITLE
rovi_master_teach demoにおいて、DashBoardが出ない件

### ISSUE THREAD

**Issue by YukiYamagata** [YOODS/rovi#56]
roslaunch rovi_master_teach demo.launch
を実行して、Rvizは起動しますが、Dash Boardが表示されません。
何かボタンを押す or ターミナルで何かを実行する
必要があるのでしょうか？

もしくは、rovi_master_teachのbranchは"devel"を使っているのですが、
"master"を使うべきなのでしょうか？

よろしくお願いします。

**Comment by Kan-Harada** [comment]
私がトライした時も出ませんでした。
https://github.com/YOODS/rovi_master_teach/blob/master/README.md
にその時の対応を追記しましたが、具体的には

> pip install tkfilebrowser --user

で解決できました。やってみてください。

**Comment by YukiYamagata** [comment]
できるようになりました。
ありがとうございます。
