### ISSUE TITLE
C. 本ツールのクライアントの作成手順について

### ISSUE THREAD

**Issue by MatuokaNaru** [YOODS/rovi#57]
本ツールのクライアントについて~/catkin_ws/src/xxx/pmjson/ のpmjsonのフォルダはどこにあるのでしょうか？そもそもxxxは今回において何に当たるのでしょうか？

**Comment by KazukiHiraizumi** [comment]
こちらREADMEは古く、実装にはほとんど一致しません。以下を見てください。
https://github.com/YOODS/rqt_param_manager/blob/devel/SPEC.md
pmconfに相当するファイル(下例ではsetup.ui)は、conf:=...にて以下のように渡します(rovi_master_teach/setup.launchより抜粋)。
~~~
conf:=$(find rovi_master_teach)/setup.ui 
~~~
