### ISSUE TITLE
camera_aravisソフトウェアトリガの失敗=>ライブモードではハード(内部)トリガとする

### ISSUE THREAD

**Issue by KazukiHiraizumi** [YOODS/rovi#6]
ソフトウェアトリガのQC-1/長時間運転試験を行っていますが、かなりの頻度でトリガがかからないことがある。監視タイマでリトライはしても、タイマーをあまり短くできない(トリガの２度入りが起きる)。
ハードウェアトリガなら安定している。時々インタバルが長い時(200〜300ミリ秒程度)があるものの、カメラの内部的なインタロックがある？ためか長時間でも問題がおきない。
結論的には、ライブ＝ハードトリガ、ということになる。

**Comment by KazukiHiraizumi** [comment]
FrameRateの設定基準はどうなっているのかな？
お客さんのプラットフォームは様々だろうから、診断機能を組み込む必要あり。

**Comment by KazukiHiraizumi** [comment]
TriggerModeをOffからOnに変えた時、FrameRateは1000に書き変わる。これはcamera_aravisのソースを直す必要あり

**Comment by take-w** [comment]
2018/3/16(金)の打ち合わせでの
　TriggerMode=Offにして、ストリーミングモードにする。
　しかし1FPSくらいでしか動かないのは？
　camera_l, camera_rではなく、片側（camera_l）だけにして、動かしてみる。

⇒
片側でも、安定して動くのは
（＝Frame error: ARV_BUFFER_STATUS_TIMEOUT
　　エラーが出ないのは）
FPS 2.0以下くらい。
（FPS 2.125や2.1なら基本大丈夫だが、たまにエラーが塊になって出る。）

**Comment by KazukiHiraizumi** [comment]
それは大問題ですね。
VMではないLinux環境でやってみましょうか？
ありますか？

**Comment by take-w** [comment]
ないです。。

3/23(金)に原田さんがセットアップ済み予定のJetsonとつないでやってみるのがいいでしょうか。

**Comment by KazukiHiraizumi** [comment]
CelelonですがNativeのLinuxPCを持っているので、次回DRで動かしてみましょう。
他のところをすすめてください

**Comment by KazukiHiraizumi** [comment]
@take-w 
解像度を下げたらどうなるかみてもらえますか？私の方はVGA(640x480)のカメラですが、これだと上のPCにaravisとimage_viewのみで50FPSくらいまでいけます。
解像度の変更はrosparamではできません。arv-toolいうのでやります。
~~~
arv-tool-0.4 control Width=640 Height=480
~~~

**Comment by take-w** [comment]
（これまでは1280x1024だったのを）
640x480にしたところ、
aravis+image_viewで、

片側だと、8FPSくらいならOK。
（8.5や9だとエラーが少し出始める。10だと明らかにエラーが出てくる。）

両側だと、4FPS & 4FPS くらいならOK。
（何もしていない状態なら6, 6くらいならOKだが、image_viewとかGUIクリックとかで少しエラーが出る。）

でした。

画素数が1/4になったからFPSも4倍まで行けるようになった、という感じでしょうか。🤔

320x240にすると、片側32, 両側16&16、とまではいかずに、OKなのはもう少し低い値になりました。
32x32だと、両側100&100でもOK。
しかし320x240でも視野が狭いし、32x32はどこが映っているのかわからない視野の狭さ。
（RoVIでどのくらいの視野の広さが必要とされているかはわかりませんが。。）

**Comment by KazukiHiraizumi** [comment]
@take-w 
いいIssueがありました
https://answers.ros.org/question/132446/aravis-camnode-frame-error-arv_buffer_status_timeout/
自分のPCでやってみましたが、１００FPSでも余裕で動くようになりました。
mtuの設定はカメラが記憶しているようなので注意ください。
paramのcamera/mtuにもあるのですが、これがあまり効いていないので、カメラに直接した方がいいです。初期値は1500なのでこれを9000にします
~~~
arv-tool-0.4 control GevSCPSPacketSize=9000
~~~
これでcamnodeを起動すると起動メッセージの最後あたりに、paramのmtuとは無関係に
~~~
[ INFO] [1521499733.508251432]:     Network mtu          = 9000
~~~
と出ます。
PC側のmtu設定は、私の古いPCだと1500が上限だったので、こっちも注意ください。

**Comment by take-w** [comment]
ありがとうございます。

そもそもGevSCPSPacketSizeの初期値が576だったので、1500にしたら少しはFPSが改善しました。
（せいぜい2倍ちょっとですが。。）

次に9000ですが、VMware Workstation Playerの限界らしく、1500より上にすると常に
Frame error: ARV_BUFFER_STATUS_TIMEOUT
でだめでした。
（ホストWindows側をJumbo Packet 9014Byteにして、Ubuntuでmtu 9000などしてもだめ。
　有料VMware vSphereだとJumbo Packetがいけるらしい。。）

詰まっている場所はわかったので、ひとまずよしとして。

開発用に、VMwareではない、ちゃんとしたUbuntu PCを用意してもらう方がいいかも・・？

**Comment by KazukiHiraizumi** [comment]
UbuntuよりLinuxMintがいいですよ。
https://linuxmint.com/
Ubuntu起源なので互換だし、普段PCもこれで済む。

**Comment by Kan-Harada** [comment]
Jetsonを使えば良い気がしますが・・・どうでしょうか?
使っていないデスクトップは一台はあった気がします。

**Comment by Kan-Harada** [comment]
MTU9000の設定はGigE Visionでは必須と聞いています。ただ、以前YJC-3でやろうとしたらできなかった。これは使っているPHY等に依存するのでは・・というところで終わっていました。

**Comment by take-w** [comment]
> 普段PCもこれで済む。
VPNがつながらない？とかいう話もありますし、完全にWindowsから移行してこれ一台、はさすがに無理かなと。

でもNEDO開発用LinuxマシンのOSとしてはMintでいいかもですね。

**Comment by take-w** [comment]
> Jetsonを使えば良い気が

Jetsonだと開発環境と動作環境がわかれてまた話がややこしくなるような。。

**Comment by take-w** [comment]
> MTU9000の設定はGigE Visionでは必須と聞いています。
でも、WindowsのeBUS Playerだと、MTUはいじらずに（Jumbo Packet Disabledで）60fps行けるわけでして。

UbuntuのeBUS Playerも60fpsまではいけないがそこそこいけるわけで、、？

camera_aravisのドライバとの絡みが？（何かよくわからなくなってきました。）

**Comment by Kan-Harada** [comment]
@take-w ノートPCならばいくつかありますがハードディスクを載せ換えて使いますか?

**Comment by take-w** [comment]
はい。適当なノートPCで。ハードディスクも適当で。
（UbuntuかMintを入れてネイティブに使います。）

まっさらハードディスクに乗せ換えて、Ubuntu or Mintを入れるって感じでしょうか。

**Comment by take-w** [comment]
2018/3/23(金)のFRONTIERノートPCにUbuntu 16, ROSなど入れて試してみました。

デフォルト状態
	PC側のmtuは1500
	arv-tool-0.4 control GevSCPSPacketSize は 576
	arv-tool-0.4 control Width Height は 1280x1024
だと、
カメラ1台でも2台でも、FPS 40くらいまでOK.
（カメラ1台でも2台でも、FPS 45だとかなりエラー。）

MTU 9000状態
	PC側のmtuは9000
	arv-tool-0.4 control GevSCPSPacketSize は 9000
	arv-tool-0.4 control Width Height は 1280x1024
だと、
カメラ2台でFPS 30, 30なら安定する。（60, 60とかはエラー多発。）

MTU 9000で解像度を下げると
	PC側のmtuは9000
	arv-tool-0.4 control GevSCPSPacketSize は 9000
	arv-tool-0.4 control Width Height は 640x480
カメラ2台でFPS 1000, 1000でも安定する。

よって、（MTUは9000にするとして、）解像度とFPSの関係としては

＜A＞
解像度：1280x1024
FPS: 30, 30

＜B＞
解像度：640x480
FPS: 1000, 1000

とかなります。

ただ、別環境ではBでも1000, 1000とか出せるとは限らないので、
結局Aを基本に考えておくのがいいでしょうか？

**Comment by take-w** [comment]
あと、
	arv-tool-0.4 control GevSCPSPacketSize は 9000
	arv-tool-0.4 control Width Height は 1280x1024
にするのは、YCAM側を再起動すると初期値に戻ってしまって、これらの値になる保証がないので、
RoVIの起動時にYCAMへコマンドを打ち込む必要がありそうです。

**Comment by KazukiHiraizumi** [comment]
私の手元にあるBaslerのカメラなら、Paramerのｍｔuがcamnode起動時に設定されますね。
PC側は1500のままでもOKそうです。送信時しか意味無いのか？

**Comment by KazukiHiraizumi** [comment]
pshift_genpc.jsでライブと13枚撮影まで実装しました。
Chatの方にコメント入れました。
カメラ２台で動かすときは、ycam1h.jsのコメントを外してください。
プロジェクタの制御はYCAMがないとテストが出来ないので、水曜日にやります。

**Comment by take-w** [comment]
> 私の手元にあるBaslerのカメラなら、Paramerのｍｔuがcamnode起動時に設定されますね。

こちらのFRONTIER PCとYCAMの組み合わせでも同様にParameterの値がarv-toolへ設定反映されました。

なので
> RoVIの起動時にYCAMへコマンドを打ち込む必要がありそうです。

は無し、で。

> PC側は1500のままでもOKそうです。送信時しか意味無いのか？

これも確認できました。
なのでPC側は特にmtuを変えるようにはGettingStarted.mdには書かないことにします。

**Comment by take-w** [comment]
あぁでも、RoVIは起動しっぱなしで、YCAMの電源をOFF->ONすると、mtu(GevSCPSPacketSize)は576とかの初期値に戻りますね。

そういうのも異常監視で見ておいて、Parameterを反映させればいいか？

**Comment by KazukiHiraizumi** [comment]
camnodeのプロセスが終了したらycam1h.jsで監視しているので再起動します。
起動時にはパラメータが再設定されると思いますが、瞬断ではプロセス終了しないのか？
そうなると異常監視にはひっかからないですが・・・・
明日見てみましょう。

**Comment by take-w** [comment]
> Parameterの値がarv-toolへ設定反映され
は、launchファイル内で
<rosparam command="load" ns="/rovi" file="$(find rovi)/yaml/rovi_rosparam_dump.yaml" />
のようにしてから
<node>で各種ノード（/rovi以下のParameterを使っている）を起動しているからですね。

ycam1h.jsの中からの起動でも同様にrosparam loadをすれば再設定されると思います。
（別の言い方をすると、単にプロセス起動だけだと再設定されないはず。）
（まぁ細かいことは明日。）

**Comment by KazukiHiraizumi** [comment]
最終的にはライブモードもソフトウェアでプロジェクタからトリガ（ワンショット）を出すようになりました
