### ISSUE TITLE
「pshift_genpc timeout AAA」が発生したらrovi再起動が必要

### ISSUE THREAD

**Issue by Kan-Harada** [YOODS/rovi#61]
YCAM3Dで位相シフトの13枚画像データ転送時に画像ロストが発生するとrovi再起動が必要となります。これは実使用上マズイです。

それとは別に転送エラーで位相シフト撮影が失敗した場合、(滅多にないことですが)自動で再撮影する機能も欲しい。

**Comment by KazukiHiraizumi** [comment]
この状態ではリトライしても同じですね。
rovi再起動ということはカメラ再接続ということ思いますが、もしaravisが切断検知すればこれは自動的に行われます。
エラーの後ストリーミングもできなくなっていれば、aravisに切断検知されずに死んでいる、という異常モードもある、ということです。
どうでしょうか？

**Comment by KazukiHiraizumi** [comment]
ramielではtimeoutエラーを保持しています。
resetリクエストでも解除されますが、エラー保持自体を止めるよう改変しました
