### ISSUE TITLE
rovi/GettingStarted.mdの改善案

### ISSUE THREAD

**Issue by YukiYamagata** [YOODS/rovi#63]
GigEインターフェース設定
●アドレス設定
項目　　　　値　　　                         備考
アドレス　　  192.168.222.100
ネットマスク　255.255.255.0
ゲートウェイ                                          設定不要
MTU             9000                              Jumboパケット対応のため

●設定方法
$ ifconfig
を実行し、インターフェース名(接続名)を取得

$ sudo vi /etc/network/interfaces
を実行し、以下の内容を変更する。
元々の記述はコメントアウトする。

●変更前
auto {取得したインターフェース名}
iface {取得したインターフェース名} inet dhcp

●変更後
auto {取得したインターフェース名}
iface {取得したインターフェース名} inet static
 address 192.168.222.100
 netmask 255.255.255.0
 mtu 9000

※上記の変更前の記述が元々ない場合は、変更後の記述を追記する。

**Comment by Kan-Harada** [comment]
/etc/network/interfacesは伝統的なdebianのネットワーク設定ファイルですが、UbuntuやMintのGUIでネットワーク設定を行った場合、/etc/NetworkManager/system-connections/にNIC毎に設定ファイルができるようです。ここを追加・削除するのが正解な気がします。ただ、両方に設定がある場合は/etc/network/interfacesが優先されるような・・・

**Comment by YukiYamagata** [comment]
nmcliコマンドでIPアドレス等の設定を行う方法を調べていて、
IPアドレスとサブネットマスクは設定できたのですが、MTUの設定方法がわかりませんでした。
ご教示頂けると幸いです。

**Comment by YukiYamagata** [comment]
また、改善案として
RoVIの実行手順のテストにおいて、以下の記述を追記するのはどうでしょうか？
私達が実際に撮像のテストをしてみて、本当に撮像できたのか確認できず不安でしたので、
以下の記述があると確認できると思います。

$ rosservice call /rovi/pshift_genpc
を実行すると、13枚の撮影画像データ(png画像)が保存される。
保存場所は「/tmp/」である。capt0*_0.pngという形式で13枚の画像が保存される。
	capt00_0.png:フラッシュと焚かないで撮った画像
	capt01_0.png,:全体をフラッシュ焚いて撮った画像
	capt02_0.png:右半分がフラッシュ焚いて撮って画像
	capt03_0.png:左10分の9ぐらいをフラッシュ焚いて撮った画像
	capt04_0.png:両端3分の1ずつをフラッシュ焚いて撮った画像
	　・・・
	test.ply:3次元の点群画像

test.plyの3次元の点群画像をLinux上で表示させたい場合は、meshlabをインストールする。
$ sudo apt-get install meshlab
$ meshlab test.ply

●生映像の表示方法
$ rosrun image_view image_view image:=/rovi/left/image_raw
でYCAMの左カメラの生映像(何も加工していない映像)を表示する。

$ rosrun image_view image_view image:=/rovi/right/image_raw
でYCAMの右カメラの生映像(何も加工していない映像)を表示する。

$ rosrun image_view image_view image:=/rovi/left(right)/image_rect
でYCAMの左右のカメラの加工映像(映像内の物体において、上下の高さを補正した映像)を表示する。

●Rvizでの表示方法
$ rviz
コマンドを実行し、Rvizを立ち上げる。

Displays→Add→By topic→/rovi/left(right)/image
をRviz上に表示させると、カメラ映像が表示できる。

Displays→Add→By topic→/rovi/ps_pc/PointCloud
をRviz上で表示するとYCAMで撮った点群情報を取得できるようになる。
	PointCloud
		Color Transformer:点群の色を設定できる。
			FlatColor：すべての点群を同じ色で表示する(Colorで色を指定(RGBデータ))
			Intensity:輝度値に合わせて、点群を表示する

PointCloudを有効にして、下記のコマンドを実行すると、点群データが表示される
(注意：デフォルトの拡大率では、拡大しすぎていて、表示されない可能性がある。そのため、縮小したり、視点は変えることによって、点群を確認できる)

catkin_ws/src/rovi/yaml/ycam3sxag.yaml の
pshift_genpc/calc/max_stepを50.0→1.0に変更すると、ノイズを少なくすることができる。
	calc以下のパラメータは点群を表示させるために決めるのに必要なパラメータ
	max_step:左右のカメラの位相差が激しいと物体と認識しない。その閾値を表す。
	ExposureTime：フラッシュを焚く時間
	Intencity：フラッシュの発光強度

$ rosparam set /rovi/pshift_genpc/calc/max_step <value>
でも、パラメータを変更できるが、rosを再起動するとデフォルト値に戻る。
パラメータの変更を保存しておく場合は、上記のcatkin_ws/src/rovi/yaml/ycam3sxag.yamlを直接変更する必要がある。
