### ISSUE TITLE
ソースコードのエンコーディングをUTF-8にする

### ISSUE THREAD

**Issue by dif-engine** [YOODS/rovi#79]
Ubuntuで一般的なエディタを使ったときにShiftJISだと文字化けしやすいので，UTF-8に変更していただけると嬉しいです．

**Comment by Kan-Harada** [comment]
noeticブランチのみですがUTF8に変更しました。srcディレクトリ以下のCのソースにShift-JISのコードがあったようです。

**Comment by dif-engine** [comment]
ご対応ありがとうございました．
