### ISSUE TITLE
共通サービスのインタフェース

### ISSUE THREAD

**Issue by KazukiHiraizumi** [YOODS/rovi#8]
RoViパッケージのノードで、以下の機能が必要であれば、共通のインタフェースに揃えたいと思います。
1. パラメータのリロード
2. 汎用コマンド
## パラメータのリロード reload
サービス名は.../reloadとします。
サービス型はROSで定義済のstd_srvs::Trigger型とします。TriggerはRequestメッセージがないので、呼び出しは下のようになります。
~~~
rosservice call .../reload
~~~
サーバ側では以下のように、spinに入る前に1回reloadを呼び出しておきましょう
~~~
std_srvs::Trigger::Request req;
std_srvs::Trigger::Response res;
reload(req,res);
ros::spin();
~~~
## 汎用コマンド parse
特に処理速度が要求されないサービスにも、いちいち型定義するのは面倒なので、文字列を投げてやってもらう的サービスを規定したいと思います。
サービス名は.../parseとします。
下のようなSyntaxです。
~~~
rosservice call .../parse cmd
rosservice call .../parse 'cmd [{"key":value}]'
~~~
使い方事例を次の投稿に書きます

**Comment by KazukiHiraizumi** [comment]
parse続き...
1. .../parseに"get"というコマンドを投げます。"get"コマンドは引数を必要としない(あるいは省略可能)とすると以下の入力となります。
~~~
rosservice call .../parse get
~~~
2. .../parseに"set"という、引数が必要なコマンドを投げます。
~~~
rosservice call .../parse 'set {"Gain":10,"TriggerMode":"On"}'
~~~
引数はJSON形式で記述します。コマンドと引数の全体を(')で括り、keyおよび文字列値は(")で括ります。

**Comment by KazukiHiraizumi** [comment]
parse続き...
parseのサーバサイドの実装例です。
~~~
rosNode.advertiseService('..../parse',rovi_srvs.dialog, (req,res)=>{
	let cmd=req.hello;
	let lbk=cmd.indexOf('{');
	let obj={};
	if(lbk>0){
		cmd=req.hello.substring(0,lbk).trim();
		obj=JSON.parse(req.hello.substring(lbk));
	}
	ros.log.info('parsed:'+cmd+' arg:'+JSON.stringify(obj));
	switch(cmd){
	case 'get':
		return new Promise((resolve)=>{
			res.answer='{Gain:100}';
			resolve(true);
		});
	case 'set':
		return Promise.resolve(true);
	}
});
~~~

**Comment by take-w** [comment]
質問です。

parseサービスは、現状はcmdとしてget/setのみ、ということは、
parse getは ROS Parameterのget
parse setは ROS Parameterのset
を行うということですよね？

例えば左側カメラのゲインを設定したい場合は
rosservice call .../parse 'set {"/rovi/cam_l/camera/Gain":10}'
という理解でよいでしょうか？
（keyはROS Parameter名そのもの。）

そして、3DのためのGain設定なら、
rosservice call .../parse 'set {"Gain":10}'
とする。
（前述の左側カメラのゲインパターンとは違い、keyは絶対パス形式ではない。
　はっきりと「"RoVI-3D-Gain"」みたいなkey文字列がよいかもしれない。）

**Comment by KazukiHiraizumi** [comment]
.../parse "string" という書式までで、stringのとこに来る、具体的なコマンドまでは規定してないです。
ノード側の実装に委ねるいうことで考えています。
ただJSなら実装も簡単なので、パラメータ設定のコマンド(set,get)だけはルール化してもよいかもしれません。
いまのところパラメータの設定＆反映のルールは
１)dynamic_reconfigure対応のノード(たぶん既存のノード)であれば、dynparam
2)YOODSで新製するものはrosparamの後、call .../reload
3)１，２以外はrosparamの後、ノードを再起動

**Comment by take-w** [comment]
誤解してました。

『各』ノードが、『自身の』 reload, parse cmdサービスを提供する、
ということですね。

なので、ユーザからのパラメータ設定は（予定通り）
rosservice call /rovi/upper/param_set "/rovi/cam_l/camera/Gain" 10
とか
rosservice call /rovi/upper/param_set {"3D-Gain":10, "3D-ExposureTimeAbs":12345}
みたいな感じで、
あとはこのupperサービスノード（mainかなにか）が、
下位のノードにparseとかreloadとかdynparamとかで振ってよきにはからう。

> パラメータ設定のコマンド(set,get)だけはルール化してもよいかも
parse paramget
parse paramset
という形で共通化するかもしれません。

**Comment by take-w** [comment]
> rosservice call /rovi/upper/param_set {"3D-Gain":10, "3D-ExposureTimeAbs":12345}
も形は合わせて（パラメータの絶対パス形式で）
> rosservice call /rovi/upper/param_set {"/rovi/3d/Gain":10, "/rovi/3d/ExposureTimeAbs":12345}
のようにすることにします。

こうすればparam dumpできる。
（実際には/rovi/3d/Gainの値などは必要に応じてカメラに設定に行く、という当初予定通り。）

**Comment by KazukiHiraizumi** [comment]
Paramer変更のNotifiierを使う
